      DOUBLE PRECISION FUNCTION DSIG(PP,WGT)
C     ****************************************************
C     
C     Generated by MadGraph 5 v. 2.0.0.beta1, 2012-11-08
C     By the MadGraph Development Team
C     Please visit us at https://launchpad.net/madgraph5
C     
C     Process: g g > h > mu+ mu- WEIGHTED=4 HIG=1 HIW=1
C     Process: c c~ > h > mu+ mu- WEIGHTED=4 HIG=1 HIW=1
C     
C     RETURNS DIFFERENTIAL CROSS SECTION 
C     FOR MULTIPLE PROCESSES IN PROCESS GROUP
C     Input:
C     pp    4 momentum of external particles
C     wgt   weight from Monte Carlo
C     Output:
C     Amplitude squared and summed
C     ****************************************************
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'nexternal.inc'
      INCLUDE 'maxamps.inc'
      REAL*8     PI
      PARAMETER (PI=3.1415926D0)
C     
C     ARGUMENTS 
C     
      DOUBLE PRECISION PP(0:3,NEXTERNAL), WGT
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,K,ICONF,IMIRROR,NPROC
      SAVE NPROC
      LOGICAL MIRRORPROCS(MAXSPROC)
      INCLUDE 'mirrorprocs.inc'
      DOUBLE PRECISION XDUM
C     
C     EXTERNAL FUNCTIONS
C     
      DOUBLE PRECISION DSIGPROC
      EXTERNAL DSIGPROC
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'
      INCLUDE 'run.inc'
C     IPROC has the present process number
      INTEGER IPROC
      COMMON/TO_MIRROR/IMIRROR, IPROC
C     ----------
C     BEGIN CODE
C     ----------
      DSIG=0D0


C     Select among the subprocesses based on PDF weight
      DO IPROC=1,MAXSPROC
        DO IMIRROR=1,2
          IF(IMIRROR.EQ.1.OR.MIRRORPROCS(IPROC))THEN
            DSIG=DSIG+DSIGPROC(PP,IPROC,IMIRROR)
            IF(IMIRROR.EQ.2)THEN
C             Need to flip back x values
              XDUM=XBK(1)
              XBK(1)=XBK(2)
              XBK(2)=XDUM
            ENDIF
          ENDIF
        ENDDO
      ENDDO


      RETURN
      END

      FUNCTION DSIGPROC(PP,IPROC,IMIRROR)
C     ****************************************************
C     RETURNS DIFFERENTIAL CROSS SECTION 
C     FOR A PROCESS
C     Input:
C     pp    4 momentum of external particles
C     wgt   weight from Monte Carlo
C     Output:
C     Amplitude squared and summed
C     ****************************************************

      IMPLICIT NONE

      INCLUDE 'nexternal.inc'
      INCLUDE 'maxamps.inc'
      INCLUDE 'coupl.inc'
      INCLUDE 'run.inc'
C     
C     ARGUMENTS 
C     
      DOUBLE PRECISION DSIGPROC
      DOUBLE PRECISION PP(0:3,NEXTERNAL), WGT
      INTEGER IPROC,IMIRROR
C     
C     GLOBAL VARIABLES
C     
C     SUBDIAG is vector of diagram numbers for this config
C     IB gives which beam is which (for mirror processes)
      INTEGER SUBDIAG(MAXSPROC),IB(2)
      COMMON/TO_SUB_DIAG/SUBDIAG,IB
C     
C     EXTERNAL FUNCTIONS
C     
      DOUBLE PRECISION DSIG1,DSIG2
      LOGICAL PASSCUTS
C     
C     LOCAL VARIABLES 
C     
      DOUBLE PRECISION P1(0:3,NEXTERNAL),XDUM
      DOUBLE PRECISION PTEMP(0:3)
      INTEGER I,J,K
      INTEGER IMODE

      IMODE=1  ! DUMMY VARIABLE
      DO I=1,NEXTERNAL
        DO J=0,3
          P1(J,I)=PP(J,I)
        ENDDO
      ENDDO

      IB(1)=1
      IB(2)=2

      IF(IMIRROR.EQ.2)THEN
        DO I=0,3
          PTEMP(I)=P1(I,1)
          P1(I,1)=P1(I,2)
          P1(I,2)=PTEMP(I)
        ENDDO
C       Flip x values 
        XDUM=XBK(1)
        XBK(1)=XBK(2)
        XBK(2)=XDUM
      ENDIF

      DSIGPROC=0D0

      IF(IPROC.EQ.1) DSIGPROC=DSIG1(P1,WGT,IMODE)  ! g g > mu+ mu-
      IF(IPROC.EQ.2) DSIGPROC=DSIG2(P1,WGT,IMODE)  ! c c~ > mu+ mu-
      RETURN
      END


