ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=3)

      DOUBLE PRECISION ME,MC,MB,MM,MH,MT,MW,MP,MTA,MZ

      COMMON/MASSES/ ME,MC,MB,MM,MH,MT,MW,MP,MTA,MZ


      DOUBLE PRECISION WTAU,WH,WW,WT,WH1,WZ

      COMMON/WIDTHS/ WTAU,WH,WW,WT,WH1,WZ


      DOUBLE COMPLEX GC_8, GC_40, GC_42

      COMMON/COUPLINGS/ GC_8, GC_40, GC_42

