ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of heftold-full'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_8 = ', GC_8
      WRITE(*,2) 'GC_40 = ', GC_40
      WRITE(*,2) 'GC_42 = ', GC_42
