ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'Gf = ', GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'lamWS = ', LAMWS
      WRITE(*,*) 'AWS = ', AWS
      WRITE(*,*) 'rhoWS = ', RHOWS
      WRITE(*,*) 'etaWS = ', ETAWS
      WRITE(*,*) 'ymc = ', YMC
      WRITE(*,*) 'ymb = ', YMB
      WRITE(*,*) 'ymt = ', YMT
      WRITE(*,*) 'yme = ', YME
      WRITE(*,*) 'ymm = ', YMM
      WRITE(*,*) 'ymtau = ', YMTAU
      WRITE(*,*) 'MC = ', MC
      WRITE(*,*) 'MT = ', MT
      WRITE(*,*) 'MB = ', MB
      WRITE(*,*) 'MZ = ', MZ
      WRITE(*,*) 'MH = ', MH
      WRITE(*,*) 'Me = ', ME
      WRITE(*,*) 'MM = ', MM
      WRITE(*,*) 'MTA = ', MTA
      WRITE(*,*) 'MP = ', MP
      WRITE(*,*) 'WT = ', WT
      WRITE(*,*) 'WZ = ', WZ
      WRITE(*,*) 'WW = ', WW
      WRITE(*,*) 'WH = ', WH
      WRITE(*,*) 'WTau = ', WTAU
      WRITE(*,*) 'WH1 = ', WH1
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'lamWS__exp__2 = ', LAMWS__EXP__2
      WRITE(*,*) 'CKM11 = ', CKM11
      WRITE(*,*) 'CKM12 = ', CKM12
      WRITE(*,*) 'complexi = ', COMPLEXI
      WRITE(*,*) 'lamWS__exp__3 = ', LAMWS__EXP__3
      WRITE(*,*) 'CKM13 = ', CKM13
      WRITE(*,*) 'CKM21 = ', CKM21
      WRITE(*,*) 'CKM22 = ', CKM22
      WRITE(*,*) 'CKM23 = ', CKM23
      WRITE(*,*) 'CKM31 = ', CKM31
      WRITE(*,*) 'CKM32 = ', CKM32
      WRITE(*,*) 'CKM33 = ', CKM33
      WRITE(*,*) 'MZ__exp__2 = ', MZ__EXP__2
      WRITE(*,*) 'MZ__exp__4 = ', MZ__EXP__4
      WRITE(*,*) 'sqrt__2 = ', SQRT__2
      WRITE(*,*) 'MH__exp__4 = ', MH__EXP__4
      WRITE(*,*) 'MT__exp__4 = ', MT__EXP__4
      WRITE(*,*) 'MH__exp__2 = ', MH__EXP__2
      WRITE(*,*) 'MT__exp__2 = ', MT__EXP__2
      WRITE(*,*) 'MH__exp__12 = ', MH__EXP__12
      WRITE(*,*) 'MH__exp__10 = ', MH__EXP__10
      WRITE(*,*) 'MH__exp__8 = ', MH__EXP__8
      WRITE(*,*) 'MH__exp__6 = ', MH__EXP__6
      WRITE(*,*) 'MT__exp__6 = ', MT__EXP__6
      WRITE(*,*) 'conjg__CKM11 = ', CONJG__CKM11
      WRITE(*,*) 'conjg__CKM12 = ', CONJG__CKM12
      WRITE(*,*) 'conjg__CKM13 = ', CONJG__CKM13
      WRITE(*,*) 'conjg__CKM21 = ', CONJG__CKM21
      WRITE(*,*) 'conjg__CKM22 = ', CONJG__CKM22
      WRITE(*,*) 'conjg__CKM23 = ', CONJG__CKM23
      WRITE(*,*) 'conjg__CKM31 = ', CONJG__CKM31
      WRITE(*,*) 'conjg__CKM32 = ', CONJG__CKM32
      WRITE(*,*) 'conjg__CKM33 = ', CONJG__CKM33
      WRITE(*,*) 'aEW = ', AEW
      WRITE(*,*) 'MW = ', MW
      WRITE(*,*) 'sqrt__aEW = ', SQRT__AEW
      WRITE(*,*) 'ee = ', EE
      WRITE(*,*) 'MW__exp__2 = ', MW__EXP__2
      WRITE(*,*) 'sw2 = ', SW2
      WRITE(*,*) 'cw = ', CW
      WRITE(*,*) 'sqrt__sw2 = ', SQRT__SW2
      WRITE(*,*) 'sw = ', SW
      WRITE(*,*) 'g1 = ', G1
      WRITE(*,*) 'gw = ', GW
      WRITE(*,*) 'v = ', V
      WRITE(*,*) 'ee__exp__2 = ', EE__EXP__2
      WRITE(*,*) 'MW__exp__12 = ', MW__EXP__12
      WRITE(*,*) 'MW__exp__10 = ', MW__EXP__10
      WRITE(*,*) 'MW__exp__8 = ', MW__EXP__8
      WRITE(*,*) 'MW__exp__6 = ', MW__EXP__6
      WRITE(*,*) 'MW__exp__4 = ', MW__EXP__4
      WRITE(*,*) 'AH = ', AH
      WRITE(*,*) 'v__exp__2 = ', V__EXP__2
      WRITE(*,*) 'lam = ', LAM
      WRITE(*,*) 'yb = ', YB
      WRITE(*,*) 'yc = ', YC
      WRITE(*,*) 'ye = ', YE
      WRITE(*,*) 'ym = ', YM
      WRITE(*,*) 'yt = ', YT
      WRITE(*,*) 'ytau = ', YTAU
      WRITE(*,*) 'muH = ', MUH
      WRITE(*,*) 'gw__exp__2 = ', GW__EXP__2
      WRITE(*,*) 'cw__exp__2 = ', CW__EXP__2
      WRITE(*,*) 'sw__exp__2 = ', SW__EXP__2
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'sqrt__aS = ', SQRT__AS
      WRITE(*,*) 'G__exp__2 = ', G__EXP__2
      WRITE(*,*) 'GH = ', GH
      WRITE(*,*) 'Gphi = ', GPHI
