###########################################################
##                                                       ##
##              ordering width information               ##
##              **************************               ##
##                                                       ##
##      Authors: Pierre Artoisenet (UCL-CP3)             ##
##               Olivier Mattelaer (UCL-CP3)             ##
##                                                       ##
###########################################################
##    file generated automatically                       ##
## single_gaussian
###########################################################
## TAG         VALUE
  THIN         mu,e
  LARGE        u,d,s,c,b,g
  X            0
