C automatic include file for card MadWeight_card.dat and ./Cards/ident_mw_card.dat

        histo = .false.
        final_prec = 5.000000d-03
        isr = 0
        nevents = 50000
        value_cut1 = 0.000000d+00
        min_prec_cut1 = 1.000000d-03
        max_it_step1 = 2
        max_it_step3 = 0
        max_it_step2 = 16
        max_it_step5 = 0
        max_it_step4 = 0
        min_prec_cut2 = 0.000000d+00
        value_cut2 = 0.000000d+00
        nwa = .false.
        use_perm = .true.
        perm_with_b = .true.
